[build-system]
requires = ["pybind11", "scikit-build-core"]
build-backend = "scikit_build_core.build"

[project]
name = "pyascend"
version = "0.0.1"
authors = [
  {name = "Vladimir Ivanov", email = "ivvl82@gmail.com"},
]
description = "Python interface for running MLIR kernels on Ascend NPU."

[project.optional-dependencies]
test = ["numpy", "pytest"]

[tool.scikit-build]
cmake.build-type = "Release"
wheel.packages = ["src/pyascend"]

[tool.pytest.ini_options]
testpaths = ["tests"]
